/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframe;

/**
 *
 * @author lloyd
 */
public class Homepage_Customer extends javax.swing.JFrame {

    /**
     * Creates new form Homepage_Customer
     */
    public Homepage_Customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewServices = new javax.swing.JButton();
        btnAddService = new javax.swing.JButton();
        btnViewaddedservice = new javax.swing.JButton();
        btnCheckout = new javax.swing.JButton();
        btnTrackOrders = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewServices.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnViewServices.setText("View Services");
        getContentPane().add(btnViewServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 190, 30));

        btnAddService.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddService.setText("Add Service");
        btnAddService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddServiceActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddService, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 190, 30));

        btnViewaddedservice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnViewaddedservice.setText("View added service");
        btnViewaddedservice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewaddedserviceActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewaddedservice, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 30));

        btnCheckout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCheckout.setText("Checkout");
        getContentPane().add(btnCheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, 30));

        btnTrackOrders.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTrackOrders.setText("Track Orders");
        getContentPane().add(btnTrackOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 190, 30));

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, -1, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/customer_homepage.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddServiceActionPerformed

    private void btnViewaddedserviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewaddedserviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewaddedserviceActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage_Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddService;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnTrackOrders;
    private javax.swing.JButton btnViewServices;
    private javax.swing.JButton btnViewaddedservice;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
